= Digilife
Adrian May <adrian.alexander.may@gmail.com>
:imagesdir: images
:toc: preamble
:css-signature: demo

As long as software can only develop by humans writing it, the intelligence of the former is limited to that of the latter.

Evolution is the only process that can result in something more intelligent than anything which has existed before.

This project is about arranging for software to evolve beyond human limits.

'''
== Goal

[Goal]
====
Intelligent, useful, internet-native, freely evolving 
software life-forms permanently established in world economy.
====

== Overview

[TIP]
.Admonition and callout icons
====
Asciidoctor can "draw" icons using {fontawesome-ref}[Font Awesome^] and CSS.

To use this feature, set the value of the `icons` document attribute to `font`.
Asciidoctor will then emit HTML markup that selects an appropriate font character from the Font Awesome font for each admonition block.

Icons can also be used {icon-inline}[inline] and {icon-attribute}[styled].
====


== Formulation


